###
# API-1 Get All todo's
GET http://localhost:8080/todos/

###
# API-2 Get todo
GET http://localhost:8080/todos/4

###
#API -3 add todo
POST http://localhost:8080/todos
Content-Type: application/json

{
  "todo": "Run",
  "priority": "MEDIUM",
  "status": "TO DO"
}
