###
# API-1 Get All todo's
GET http://localhost:8080/todos/

###
# API-2 Get todo
GET http://localhost:8080/todos/11

###
#API -3 Add todo
POST http://localhost:8080/todos
Content-Type: application/json

{
  "todo": "Complete the Setup of project and MySQL in my PC",
  "priority": "HIGH",
  "status": "DONE"
}

###
#API-4 Update todo
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "status": "DONE",
  "priority": "MEDIUM"
}

###
# API-5 Get todo
DELETE http://localhost:8080/todos/10